name: sans_master_tables
description: "Development version of the first Sans Master app: Tables."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.24.9
  logger: ^2.4.0

flutter:
  uses-material-design: true
